//! The landing's statusline demo embeds REAL renderer output: the committed
//! fragment file is generated by darkrun-cli's `gen_statusline_demo_html`
//! (run explicitly), and this guard keeps the contract honest — three
//! scenarios present, real ANSI-derived spans, no hand-faked chips.

const FRAGMENTS: &str = include_str!("../content/statusline-demo.html");

#[test]
fn all_three_scenarios_are_present_in_both_themes() {
    for key in ["manufacture", "feedback", "gated"] {
        assert!(
            FRAGMENTS.contains(&format!("<!--scenario:{key}-->")),
            "missing scenario {key}"
        );
        assert!(
            FRAGMENTS.contains(&format!("<!--scenario:{key}-light-->")),
            "missing light variant of {key}"
        );
    }
}

#[test]
fn light_variants_deepen_the_washy_accent() {
    // On a white terminal the cyan accent (256-color 81, #5fd7ff) washes out;
    // the light fragments carry the deepened accent instead.
    let light_at = FRAGMENTS.find("<!--scenario:manufacture-light-->").unwrap();
    let light = &FRAGMENTS[light_at..];
    assert!(light.contains("#0087af"), "deepened accent in light fragments");
    assert!(
        !light.contains("#5fd7ff"),
        "no washy cyan left in the light fragments"
    );
}

#[test]
fn fragments_are_renderer_output_not_mockups() {
    // The wordmark spans the renderer emits (dark + run in the brand cyan).
    assert!(FRAGMENTS.contains(">dark</span>"), "wordmark dark half");
    assert!(FRAGMENTS.contains(">run</span>"), "wordmark run half");
    // The second-line pool leader and the beat pips survive conversion.
    assert!(FRAGMENTS.contains('\u{21b3}'), "the ↳ pool leader");
    assert!(FRAGMENTS.contains('\u{25b0}'), "filled beat pips");
    // The gate scenario carries the Π doorway.
    assert!(FRAGMENTS.contains('\u{03a0}'), "the Π gate glyph");
    // Severity chips: the blocker mark.
    assert!(FRAGMENTS.contains("fb-01"), "the feedback chip id");
    // Generated, not hand-edited.
    assert!(FRAGMENTS.starts_with("<!-- GENERATED"));
}
