//! The landing's statusline demo embeds REAL renderer output: the committed
//! fragment file is generated by darkrun-cli's `gen_statusline_demo_html`
//! (run explicitly), and this guard keeps the contract honest — three
//! scenarios present, real ANSI-derived spans, no hand-faked chips.

const FRAGMENTS: &str = include_str!("../content/statusline-demo.html");

#[test]
fn all_three_scenarios_are_present() {
    for key in ["manufacture", "feedback", "gated"] {
        assert!(
            FRAGMENTS.contains(&format!("<!--scenario:{key}-->")),
            "missing scenario {key}"
        );
    }
}

#[test]
fn fragments_are_renderer_output_not_mockups() {
    // The wordmark spans the renderer emits (dark + run in the brand cyan).
    assert!(FRAGMENTS.contains(">dark</span>"), "wordmark dark half");
    assert!(FRAGMENTS.contains(">run</span>"), "wordmark run half");
    // The second-line pool leader and the beat pips survive conversion.
    assert!(FRAGMENTS.contains('\u{21b3}'), "the ↳ pool leader");
    assert!(FRAGMENTS.contains('\u{25b0}'), "filled beat pips");
    // The gate scenario carries the Π doorway.
    assert!(FRAGMENTS.contains('\u{03a0}'), "the Π gate glyph");
    // Severity chips: the blocker mark.
    assert!(FRAGMENTS.contains("fb-01"), "the feedback chip id");
    // Generated, not hand-edited.
    assert!(FRAGMENTS.starts_with("<!-- GENERATED"));
}
